#!/bin/sh

dotFilesDir="$(dirname $0)"

# TODO : make this script work on windows (msysgit or cygwin)
# get required packages (only for ubuntu)
echo "====[ Installing Required Packages ]==="
sudo apt-get install --yes --force-yes \
    bash      \
    zsh       \
    git       \
    tree      \
    vim       \
    vim-gtk   \
    curl      \
    htop      \
    ack-grep  

# TODO : install to "~/.dotfiles" by default, or to folder provided as 1st parameter
# - clone from git repository
# - git submodule update --init #sould be done from cloned folder

echo "====[ Change default shell to ZSH ]==="
chsh -s /bin/zsh

echo "====[ Create Symbolic Links ]==="

# TODO : only create links if those features are enabled
ln -sfv $dotFilesDir/_vim/.vim   $HOME/.vim      
ln -sfv $dotFilesDir/_vim/.vimrc $HOME/.vimrc
ln -sfv $dotFilesDir/_oh-my-zsh  $HOME/.oh-my-zsh 
ln -sfv $dotFilesDir/_zshrc      $HOME/.zshrc     


# TODO : create links for "ack" and "d" in ~/bin

