#!/bin/sh

# get required packages
echo "====[ Installing Required Packages ]==="
sudo apt-get install --yes tree zsh bash git vim-gtk vim

echo "====[ Change default shell to ZSH ]==="
chsh -s /bin/zsh

echo "====[ Create Symbolic Links ]==="

dotFilesDir=$(dirname $0)

ln -sfv $dotFilesDir/_vim/_vim   $HOME/.vimrc     
ln -sfv $dotFilesDir/_vim/_vimrc $HOME/.vim       
ln -sfv $dotFilesDir/_oh-my-zsh  $HOME/.oh-my-zsh 
ln -sfv $dotFilesDir/_zshrc      $HOME/.zshrc     

